### PR TITLE
fix: hide delete button for tbz trees

### LINKED ISSUE #454: Hide delete option to delete a tree if it is not manually created

### PR DESCRIPTION
**Pull request by Zoka-tech**
Close #454

### CODE REVIEW

File: frontend/src/components/tree/TreeUpdate.tsx [hunk 1]
```diff
@@ -104,11 +104,13 @@ const TreeUpdate = ({ treeId }: TreeUpdateProps) => {
         />
       </section>
 
-      <DeleteSection
-        mutationFn={handleDeleteTree}
-        entityName="der Baum"
-        redirectUrl={{ to: '/map' }}
-      />
+      {initForm?.provider == null && (
```
Comment (doriengr) [inline frontend/src/components/tree/TreeUpdate.tsx:107]: You can simply do `!initForm?.provider`

**Review by doriengr — CHANGES_REQUESTED** [review]

**Review by doriengr — APPROVED** [review]
